spring:
  application:
    name: SSE-Test
  redis:
    host: my-redis-master.redis.svc.cluster.local
    port: 6379
    database: 0
    timeout: 2000
    password: ${REDIS_PASSWORD}
    channel:
      sse: sse-channel
server:
  servlet:
    context-path: /sse
  port: 8080

